#!mainFile "OverPainter.opy"

# ------------ Definitions ------------
#!define Words A

# ------------ Global Var --------------
globalvar Words
globalvar Theme
globalvar SelectTime
globalvar PaintTime
globalvar VoteTime
globalvar Time
globalvar Goal

# ------------ Player Var --------------
playervar pen_size
playervar pen_color
playervar pen_shape
playervar last_pos

# -------------- Subrutine --------------
