#!mainFile "OvxelArt.opy"

# ------------ Definitions ------------


# ------------ Global Var --------------
globalvar i
globalvar j
globalvar Init
globalvar Pixels
globalvar PixelsPos
globalvar PixelsNumber
globalvar PixelsText
globalvar ColorPalette
globalvar Created
globalvar MaxNumber
globalvar PaintedNumber

# ------------ Player Var --------------
playervar color
playervar click_pos
playervar num
playervar color_hud
playervar number_hud

# -------------- Subrutine --------------
