#!mainFile "OvxelArt.opy"

# ------------ Definitions ------------


# ------------ Global Var --------------
globalvar i
globalvar j
globalvar Init
globalvar Dots
globalvar DotsPos
globalvar DotsNumber
globalvar DotsNumberText
globalvar Text
globalvar ColorPalette

# ------------ Player Var --------------
playervar color
playervar click_pos
playervar mouse_pos
playervar dots_number
playervar test
playervar num
playervar color_hud

# -------------- Subrutine --------------
